services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: marineflow
      POSTGRES_USER: marineflow
      POSTGRES_PASSWORD: marineflow
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
